import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased flex-grow`}
      >
        <header>
          <h1 className="text-4xl w-full h-14 bg-gray-50">Navbar</h1>
        </header>

        <main>
        {children}
        </main>
        <footer className="min-h-full bg-gray-100 flex flex-col justify-end items-end p-4">
  <p className="text-end">Footer</p>
</footer>

      </body>
    </html>
  );
}
